name: Check Workflows

on:
  push:
    branches:
      - main
      - 'renovate/**'
    paths:
      - '.github/workflows/**.yml'

  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/**.yml'

  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Run actionlint
        run: |
          # add problem matcher for actionlint
          wget https://raw.githubusercontent.com/rhysd/actionlint/main/.github/actionlint-matcher.json \
            -O actionlint-matcher.json
          echo "::add-matcher::actionlint-matcher.json"

          # download and run actionlint
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -verbose -color
