name: Check

on:
  push:
    branches:
      - main
      - 'renovate/**'
    paths:
      - '**.js'
      - package.json
      - pnpm-lock.ya?ml
      - tsconfig.json

  pull_request:
    branches:
      - main
    paths:
      - '**.js'
      - package.json
      - pnpm-lock.ya?ml
      - tsconfig.json

  workflow_dispatch:
  workflow_call:

jobs:
  lint-and-check:
    name: Lint & Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup pnpm
        uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm run lint

      - name: Run check
        run: pnpm run check

      - name: Run self-check
        run: pnpm run self-check
